name: $(BuildID)

trigger:
  branches:
    include:
    - feature/*
    - qa
    - stage
    - fix/*
  paths:
    exclude:
    - '*.md'
    - 'backends/*'
    - 'images/*'
    - '.github/*'
    - 'docs/*'

stages:
- template: stages/ci.yaml