name: $(BuildID)

trigger: none

pr:
- dev 

variables:
- group: terraform-key-vault-cred
- template: global-vars/global.yaml


stages:
  - template: stages/ci.yaml
  - template: stages/pr.yaml
  - template: stages/add-git-tag.yaml
    parameters:
      tagFormat: GitVersion.SemVer
      tagDescription: "feature to devolopment Branch"