name: $(BuildID)

trigger: none

pr:
- master

variables:
  - group: prod-demo-key-vault-cred
  - template: global-vars/global.yaml
  
stages:
  - template: stages/ci.yaml
  - template: stages/pr.yaml
  - template: stages/add-git-tag.yaml
    parameters:
      tagFormat: GitVersion.SemVer
      tagDescription: "devolopment to master Branch"