name: $(BuildID)

#Checks regularly for any manual non Infrastructure as Code changes.

trigger: none
pr: none

schedules:
- cron: "0 0 * * *"
  displayName: Daily Midnight Build
  branches:
    include:
    - main
    - dev
  always: true

variables:
- group: terraform-key-vault-cred

steps:
- template: steps/confirm-kv-load.yaml
- template: steps/terraform-init.yaml
- template: steps/terraform-plan.yaml
  parameters:
    extraFlags: -detailed-exitcode # Drift Detection

