name: $(BuildID)

#Checks regularly for any manual non Infrastructure as Code changes.

trigger: none
pr: none

schedules:
- cron: "*/5 * * * *"
  displayName: Daily 5mins Build
  branches:
    include:
    - main
    - dev
  always: true

variables:
- group: terraform-key-vault-cred

steps:
- template: steps/demo-init.yaml
- template: steps/demo-plan.yaml
  parameters:
    extraFlags: -detailed-exitcode # Drift Detection

