name: $(BuildID)

#Checks regularly for any manual non Infrastructure as Code changes.

trigger: none
pr: none

schedules:
- cron: "*/5 * * * *"
  displayName: Daily 5mins Build
  branches:
    include:
    - main
    - dev
  always: true

variables:
- template: global-vars/global.yaml

# Conditional uses ${{ }} syntax in order to be processed at compile time
# in order to work for loading variable groups. For details see:
# # https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#understand-variable-syntax
- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/dev') }}:
  - group: terraform-key-vault-cred
- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
  - group: prod-demo-key-vault-cred

steps:
- template: steps/demo-init.yaml
- template: steps/demo-plan.yaml
  parameters:
    extraFlags: -detailed-exitcode # Drift Detection

